env:
    BUILD_HOST: Kernel-CI
    BUILD_USER: AzurE
    CIRRUS_CLONE_DEPTH: 1

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Kernel-CI"
  #trigger_type: manual
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 20G

  env_script:
      - cat /etc/os*
      - env

  sync_script:
      - git config --global user.name "AzurE-007"
      - git config --global user.email "azurehelper01@gmail.com"
      - git clone https://github.com/AzurE-007/kernel_xiaomi_raphael.git -b android11 kernel && cd kernel
  
  build_script:
      curl -sL https://raw.githubusercontent.com/AzurE-007/kraken_test/main/build.sh | bash

